<?php
declare(strict_types=1);

namespace BlaCloud;

/**
 * Reads and writes config/config.php (a PHP file returning an array,
 * so it can never be downloaded as plain text by a misconfigured server).
 */
final class Config
{
    private static ?array $data = null;

    public static function path(): string
    {
        return BLA_ROOT . '/config/config.php';
    }

    public static function isInstalled(): bool
    {
        return (bool) self::get('installed', false);
    }

    public static function all(): array
    {
        if (self::$data === null) {
            $file = self::path();
            self::$data = is_file($file) ? (array) (require $file) : [];
        }
        return self::$data;
    }

    public static function get(string $key, mixed $default = null): mixed
    {
        $data = self::all();
        foreach (explode('.', $key) as $part) {
            if (!is_array($data) || !array_key_exists($part, $data)) {
                return $default;
            }
            $data = $data[$part];
        }
        return $data;
    }

    /** Atomically write the full config array. */
    public static function write(array $config): void
    {
        $php = "<?php\n// BLA-Cloud configuration. Generated by the setup wizard.\n"
             . "// Keep this file private: it contains your encryption key.\n"
             . 'return ' . var_export($config, true) . ";\n";
        $file = self::path();
        $tmp  = $file . '.tmp-' . bin2hex(random_bytes(4));
        if (file_put_contents($tmp, $php, LOCK_EX) === false) {
            throw new \RuntimeException('Could not write the configuration file. Check that the config folder is writable.');
        }
        @chmod($tmp, 0640);
        if (!rename($tmp, $file)) {
            @unlink($tmp);
            throw new \RuntimeException('Could not save the configuration file.');
        }
        if (function_exists('opcache_invalidate')) {
            @opcache_invalidate($file, true);
        }
        self::$data = $config;
    }

    public static function set(string $key, mixed $value): void
    {
        $config = self::all();
        $config[$key] = $value;
        self::write($config);
    }
}
